### ISSUE TITLE
Improve pad placeholder behaviour

### ISSUE THREAD

**Issue by atd** [P2Pvalue/pear2pear#112]
See https://github.com/P2Pvalue/angular-swellrt/issues/18

**Comment by atfornes** [comment]
https://github.com/P2Pvalue/angular-swellrt/commit/da1ecf372ed64f61e22fa5110bf2705611a9e160 solves this. It does not hide placeholder on focus. However, if all text is erase, the placeholder does not appear again until a blur event occur.

I believe it is good enough behavior, and since it is difficult to consider the case previously exposed, I will close the issue whtih this fix. @atd, please open the issue again if you believe that it still needs to be fixed.

**Comment by atd** [comment]
@atfornes I agree that it is good enough. The main reason was to be able to focus the pad on new project creation, and still displaying the placeholder

However I would expect its behaviour to be consistent with other placeholders. So I would keep https://github.com/P2Pvalue/angular-swellrt/issues/18 opened
