### ISSUE TITLE
Bottom nav in project views

### ISSUE THREAD

**Issue by atd** [P2Pvalue/pear2pear#63]
Is there any rationale for https://github.com/P2Pvalue/pear2pear/commit/e5f382590c96f3149c953eaf957bdab37e90c451 ?

When working on the pad, I want more space. Those buttons are just too big, and I am not interested in going to Crowddoing. Mydoing is just one tap away in back button.

**Comment by atfornes** [comment]
The first approach was not to include it. Later, it was added to allow to navigate to crowddoing from pad/chat view as it was initially designed. I am happy to revert this change, since I agree with the need of space in the pad/chat. Maybe we can keep it for bigger screens and hide it in smaller.

@pablojan, what is your opinion on this?
